### ISSUE TITLE
control 12 seven segment

### ISSUE THREAD

**Issue by koztz** [Pyntoo/ShiftDisplay#15]
Hi Miguel, many thank for your library that help me so much. But I need some of your support, i want to create 3 different clock, which have 4 seven segment each.

How can i achieve this while the maximum digit of the lib. is 8 ?

**Comment by bamboo-master** [comment]
You can connect as many of them as you want.
![image](https://user-images.githubusercontent.com/81521477/144879157-3eefda90-4ea4-4602-b129-12f4562624b6.png)

**Comment by koztz** [comment]
Hi Bamboo-master....

Many thanks for your reply and support....
